// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Lfnh27P_KPnfKfxJYIpV5xr6O3XbMww',
    appId: '1:133652858240:web:137957e5dc5df2016aad65',
    messagingSenderId: '133652858240',
    projectId: 'ledcubeapp-db',
    authDomain: 'ledcubeapp-db.firebaseapp.com',
    databaseURL: 'https://ledcubeapp-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ledcubeapp-db.appspot.com',
    measurementId: 'G-STV6F29F4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcJrL9QMMa5F1rGGBHW4InldEDTvGDoFg',
    appId: '1:133652858240:android:d9e4b5d1ab1fa9e56aad65',
    messagingSenderId: '133652858240',
    projectId: 'ledcubeapp-db',
    databaseURL: 'https://ledcubeapp-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ledcubeapp-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxomw4ziIkbrGgZubx2okyIE02i6Ak1Kg',
    appId: '1:133652858240:ios:666796fced0fc27f6aad65',
    messagingSenderId: '133652858240',
    projectId: 'ledcubeapp-db',
    databaseURL: 'https://ledcubeapp-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ledcubeapp-db.appspot.com',
    iosClientId: '133652858240-i4k8ms1sprv2n2ptona8hd5cmm1b8b28.apps.googleusercontent.com',
    iosBundleId: 'com.example.ledcubeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxomw4ziIkbrGgZubx2okyIE02i6Ak1Kg',
    appId: '1:133652858240:ios:666796fced0fc27f6aad65',
    messagingSenderId: '133652858240',
    projectId: 'ledcubeapp-db',
    databaseURL: 'https://ledcubeapp-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ledcubeapp-db.appspot.com',
    iosClientId: '133652858240-i4k8ms1sprv2n2ptona8hd5cmm1b8b28.apps.googleusercontent.com',
    iosBundleId: 'com.example.ledcubeapp',
  );
}
