// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzdR13UwkMO_d6vHFcdXufZ9Wc5t5-Gro',
    appId: '1:937618905345:web:fb49835d3632e40c3ca300',
    messagingSenderId: '937618905345',
    projectId: 'ledcube-b9645',
    authDomain: 'ledcube-b9645.firebaseapp.com',
    databaseURL: 'https://ledcube-b9645-default-rtdb.firebaseio.com',
    storageBucket: 'ledcube-b9645.appspot.com',
    measurementId: 'G-6N47Q23E2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzYwXsz0OeG4ZETXuMOgyEWRw37-oKqM',
    appId: '1:937618905345:android:413f039a8c7735223ca300',
    messagingSenderId: '937618905345',
    projectId: 'ledcube-b9645',
    databaseURL: 'https://ledcube-b9645-default-rtdb.firebaseio.com',
    storageBucket: 'ledcube-b9645.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL-19-ZZ0eBLviaaddTkIKDZtt_SJ65AM',
    appId: '1:937618905345:ios:5c39714ec5b6bdf43ca300',
    messagingSenderId: '937618905345',
    projectId: 'ledcube-b9645',
    databaseURL: 'https://ledcube-b9645-default-rtdb.firebaseio.com',
    storageBucket: 'ledcube-b9645.appspot.com',
    iosBundleId: 'com.example.ledcubeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL-19-ZZ0eBLviaaddTkIKDZtt_SJ65AM',
    appId: '1:937618905345:ios:5c39714ec5b6bdf43ca300',
    messagingSenderId: '937618905345',
    projectId: 'ledcube-b9645',
    databaseURL: 'https://ledcube-b9645-default-rtdb.firebaseio.com',
    storageBucket: 'ledcube-b9645.appspot.com',
    iosBundleId: 'com.example.ledcubeapp',
  );
}
